import type { CompareResponse } from '../../types/document'
import { AskCompareQuestionPanel } from './AskCompareQuestionPanel'

interface ComparisonResultsProps {
  result: CompareResponse
  jobIds: string[]
  onReset: () => void
}

export function ComparisonResults({ result, jobIds, onReset }: ComparisonResultsProps) {
  return (
    <div className="space-y-6">
      {/* Header Summary */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-4">
          <div className="flex items-center gap-2">
            <span className="h-2 w-2 rounded-full bg-slate-900" />
            <h2 className="text-base font-semibold text-slate-900">
              Comparing {result.documents.length} documents
            </h2>
          </div>
          <span
            className="rounded-lg border border-teal-200 bg-teal-50 px-2.5 py-1 text-xs font-medium text-teal-800"
            title={
              result.ai_provider === 'fallback'
                ? 'Extractive comparison'
                : `Generated by ${result.ai_provider}`
            }
          >
            {result.ai_provider === 'fallback' ? 'Local Extractive Model' : `Engine: ${result.ai_provider}`}
          </span>
        </div>

        <div className="mt-3 flex flex-wrap items-center gap-1.5 text-xs text-slate-500">
          <span className="font-semibold uppercase tracking-wider text-slate-400">Sources:</span>
          <span>{result.documents.join(', ')}</span>
        </div>

        <p className="mt-4 text-sm leading-relaxed text-slate-700 sm:text-base">
          {result.comparison_summary}
        </p>
      </div>

      {/* Similarities Card */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-4">
          <span className="h-2 w-2 rounded-full bg-emerald-600" />
          <h3 className="text-sm font-semibold uppercase tracking-wider text-slate-900">Similarities</h3>
        </div>
        <ul className="mt-5 space-y-3">
          {result.similarities.map((item, index) => (
            <li key={index} className="flex items-start gap-3 text-sm text-slate-700 leading-relaxed">
              <span
                aria-hidden="true"
                className="mt-1 flex h-4 w-4 flex-shrink-0 items-center justify-center rounded-full border border-emerald-200 bg-emerald-50 text-[10px] font-bold text-emerald-700"
              >
                ✓
              </span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Differences Card */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 shadow-sm">
        <div className="flex items-center gap-2 border-b border-slate-100 pb-4">
          <span className="h-2 w-2 rounded-full bg-indigo-600" />
          <h3 className="text-sm font-semibold uppercase tracking-wider text-slate-900">Differences</h3>
        </div>
        <ul className="mt-5 space-y-3">
          {result.differences.map((item, index) => (
            <li key={index} className="flex items-start gap-3 text-sm text-slate-700 leading-relaxed">
              <span
                aria-hidden="true"
                className="mt-1 flex h-4 w-4 flex-shrink-0 items-center justify-center rounded-full border border-indigo-200 bg-indigo-50 text-[10px] font-bold text-indigo-700"
              >
                ≠
              </span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Action Footer */}
      <div className="flex justify-end rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <button
          type="button"
          onClick={onReset}
          className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-2.5 text-xs font-semibold text-white shadow-sm transition-all hover:bg-slate-800 active:scale-[0.99] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-900"
        >
          Compare different documents
        </button>
      </div>

      {/* Multi-Document Q&A Area */}
      <AskCompareQuestionPanel jobIds={jobIds} />
    </div>
  )
}
